[package]
name = "crabioware-metagame"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
# agb = { workspace = true }
agb = { path = "../../../../agb/agb" }
# crabioware-core = { path = "../crabioware-core/" }
