name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: nightly

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set CARGO_TARGET_DIR
        run: echo "CARGO_TARGET_DIR=$HOME/target" >> $GITHUB_ENV
      - name: Install Rust 
        run: |
          rustup toolchain install nightly
          rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rust-src rustfmt clippy
          cargo install agb-gbafix
      - uses: extractions/setup-just@v2
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/
            ~/.cargo/git/
            $CARGO_TARGET_DIR
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: |
          just build-roms
